package com.wstxda.clippy.cleaner.providers

object ShortenerRegexProvider {
    val shortenerRegexes = listOf(
        Regex("ad[_\\-]?id", RegexOption.IGNORE_CASE),
        Regex("affiliate[_\\-]?id", RegexOption.IGNORE_CASE),
        Regex("aff\\w+", RegexOption.IGNORE_CASE),
        Regex("(ad|advertising|ads|campaign)[-_]?\\w+", RegexOption.IGNORE_CASE),
        Regex("click_id", RegexOption.IGNORE_CASE),
        Regex("(clid|irclickid|click_id|clickid)", RegexOption.IGNORE_CASE),
        Regex("cookie[_\\-]?id", RegexOption.IGNORE_CASE),
        Regex("device[_\\-]?id", RegexOption.IGNORE_CASE),
        Regex("fbclid", RegexOption.IGNORE_CASE),
        Regex("feature", RegexOption.IGNORE_CASE),
        Regex("full_url", RegexOption.IGNORE_CASE),
        Regex("gclid", RegexOption.IGNORE_CASE),
        Regex("hash[_\\-]?id", RegexOption.IGNORE_CASE),
        Regex("keyword", RegexOption.IGNORE_CASE),
        Regex("(lead|session|transaction)[-_]?id", RegexOption.IGNORE_CASE),
        Regex("(msclkid|sid)", RegexOption.IGNORE_CASE),
        Regex("ref", RegexOption.IGNORE_CASE),
        Regex("referral[_\\-]?code", RegexOption.IGNORE_CASE),
        Regex("referrer[_\\-]?id", RegexOption.IGNORE_CASE),
        Regex("session[_\\-]?id", RegexOption.IGNORE_CASE),
        Regex("source[_\\-]?id", RegexOption.IGNORE_CASE),
        Regex("tracking[_\\-]?id", RegexOption.IGNORE_CASE),
        Regex("trk[_\\-]?\\w+", RegexOption.IGNORE_CASE),
        Regex("utm_(adgroup|campaign|content|medium|ref|source|term|term_id)", RegexOption.IGNORE_CASE),
        Regex("user[_\\-]?id", RegexOption.IGNORE_CASE),
        Regex("visitor[_\\-]?id", RegexOption.IGNORE_CASE),
        Regex("_hs(enc|mi)", RegexOption.IGNORE_CASE),
        Regex("hs(fp|sc|cta)", RegexOption.IGNORE_CASE),
        Regex("elqTrack(Id)?", RegexOption.IGNORE_CASE),
        Regex("spm(_id_from)?", RegexOption.IGNORE_CASE),
        Regex("spm", RegexOption.IGNORE_CASE),
        Regex("sc(_\\w+)?", RegexOption.IGNORE_CASE),
        Regex("sp(report|job|user|mailing)?id", RegexOption.IGNORE_CASE),
        Regex("share(_\\w+)?", RegexOption.IGNORE_CASE),
        Regex("ved|vet", RegexOption.IGNORE_CASE),
        Regex("cvid|ocid|mbid", RegexOption.IGNORE_CASE),
        Regex("rb_clickid", RegexOption.IGNORE_CASE),
        Regex("wickedid|vero", RegexOption.IGNORE_CASE),
        Regex("_openstat", RegexOption.IGNORE_CASE)
    )
}